-- AbioStore shared product database
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Women','Men','Children')),
  price integer not null default 0 check (price >= 0),
  old_price integer,
  tag text default '',
  color text default '',
  sizes text[] not null default '{}',
  description text not null default '',
  stock integer not null default 0 check (stock >= 0),
  image text not null default '',
  images text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category);
create index if not exists products_created_at_idx on public.products(created_at desc);

alter table public.admins enable row level security;
alter table public.products enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admins
    where user_id = auth.uid()
  );
$$;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products for delete
to authenticated
using (public.is_admin());

-- Product images are public to shoppers, but only admins can upload/change/delete them.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Anyone can view product images" on storage.objects;
create policy "Anyone can view product images"
on storage.objects for select
to public
using (bucket_id = 'product-images');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'product-images' and public.is_admin())
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images' and public.is_admin());

-- Starter catalogue. These are the products currently used by the site.
insert into public.products
  (id, name, category, price, old_price, tag, color, sizes, description, stock, image, images)
values
  (1, 'Aurelia Satin Dress', 'Women', 68500, 79000, 'Bestseller', 'Champagne', array['S','M','L','XL'], 'Fluid satin with a soft drape, sculpted waist and an effortless evening silhouette.', 10, 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85', array['https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85']),
  (2, 'Noir Tailored Set', 'Women', 92000, null, 'New', 'Black', array['S','M','L'], 'A sharp two-piece set cut for a clean, confident silhouette from day to dinner.', 10, 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85', array['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85']),
  (3, 'Edo Linen Shirt', 'Men', 42000, null, 'Essential', 'Sand', array['M','L','XL','XXL'], 'Breathable premium linen with relaxed tailoring and a beautifully understated finish.', 10, 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=85', array['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=85']),
  (4, 'Luna Pleated Midi', 'Women', 57500, null, '', 'Ivory', array['S','M','L','XL'], 'A feminine pleated midi designed to move beautifully through every occasion.', 10, 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85', array['https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85']),
  (5, 'Atlas Knit Polo', 'Men', 38500, null, 'New', 'Olive', array['M','L','XL','XXL'], 'Textured knit polo with a refined collar and easy luxury for everyday wear.', 10, 'https://images.unsplash.com/photo-1627225924765-552d49cf47ad?auto=format&fit=crop&w=900&q=85', array['https://images.unsplash.com/photo-1627225924765-552d49cf47ad?auto=format&fit=crop&w=900&q=85']),
  (6, 'Mini Muse Set', 'Children', 29500, null, '', 'Blush', array['2Y','4Y','6Y','8Y','10Y'], 'Playful, polished and made for little celebrations and big personalities.', 10, 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=85', array['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=85']),
  (7, 'Sienna Occasion Gown', 'Women', 110000, null, 'Limited', 'Terracotta', array['S','M','L'], 'Statement occasionwear with a dramatic neckline and graceful floor-length fall.', 10, 'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?auto=format&fit=crop&w=900&q=85', array['https://images.unsplash.com/photo-1581044777550-4cfa60707c03?auto=format&fit=crop&w=900&q=85']),
  (8, 'Monarch Relaxed Suit', 'Men', 125000, null, 'Signature', 'Stone', array['M','L','XL','XXL'], 'Relaxed modern tailoring with a soft shoulder and versatile separates.', 10, 'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=85', array['https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=900&q=85'])
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  greatest((select coalesce(max(id), 1) from public.products), 1),
  true
);
